// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowBlockRule(arg1) {
  return window['go']['main']['App']['AddAllowBlockRule'](arg1);
}

export function AddBreakpointRule(arg1) {
  return window['go']['main']['App']['AddBreakpointRule'](arg1);
}

export function AddMapLocalRule(arg1) {
  return window['go']['main']['App']['AddMapLocalRule'](arg1);
}

export function AddReverseProxyRule(arg1) {
  return window['go']['main']['App']['AddReverseProxyRule'](arg1);
}

export function AddScript(arg1) {
  return window['go']['main']['App']['AddScript'](arg1);
}

export function AddUpstreamProxy(arg1) {
  return window['go']['main']['App']['AddUpstreamProxy'](arg1);
}

export function CancelBreakpoint(arg1) {
  return window['go']['main']['App']['CancelBreakpoint'](arg1);
}

export function ClearFlows() {
  return window['go']['main']['App']['ClearFlows']();
}

export function DecryptRequestBody(arg1, arg2) {
  return window['go']['main']['App']['DecryptRequestBody'](arg1, arg2);
}

export function DecryptResponseBody(arg1, arg2) {
  return window['go']['main']['App']['DecryptResponseBody'](arg1, arg2);
}

export function ExportFlows(arg1) {
  return window['go']['main']['App']['ExportFlows'](arg1);
}

export function ExportFlowsToHAR(arg1) {
  return window['go']['main']['App']['ExportFlowsToHAR'](arg1);
}

export function GetActiveBreakpoints() {
  return window['go']['main']['App']['GetActiveBreakpoints']();
}

export function GetAllScripts() {
  return window['go']['main']['App']['GetAllScripts']();
}

export function GetAllowBlockMode() {
  return window['go']['main']['App']['GetAllowBlockMode']();
}

export function GetAllowBlockRules() {
  return window['go']['main']['App']['GetAllowBlockRules']();
}

export function GetBreakpointRules() {
  return window['go']['main']['App']['GetBreakpointRules']();
}

export function GetCACertInstallInstructions() {
  return window['go']['main']['App']['GetCACertInstallInstructions']();
}

export function GetCACertPath() {
  return window['go']['main']['App']['GetCACertPath']();
}

export function GetFlowByID(arg1) {
  return window['go']['main']['App']['GetFlowByID'](arg1);
}

export function GetFlows() {
  return window['go']['main']['App']['GetFlows']();
}

export function GetMapLocalRules() {
  return window['go']['main']['App']['GetMapLocalRules']();
}

export function GetPinnedFlows() {
  return window['go']['main']['App']['GetPinnedFlows']();
}

export function GetProxyPort() {
  return window['go']['main']['App']['GetProxyPort']();
}

export function GetReverseProxyRules() {
  return window['go']['main']['App']['GetReverseProxyRules']();
}

export function GetUpstreamProxies() {
  return window['go']['main']['App']['GetUpstreamProxies']();
}

export function ImportHARToFlows(arg1) {
  return window['go']['main']['App']['ImportHARToFlows'](arg1);
}

export function IsCACertInstalled() {
  return window['go']['main']['App']['IsCACertInstalled']();
}

export function IsProxyRunning() {
  return window['go']['main']['App']['IsProxyRunning']();
}

export function ModifyAndReplayFlow(arg1, arg2) {
  return window['go']['main']['App']['ModifyAndReplayFlow'](arg1, arg2);
}

export function PinFlow(arg1) {
  return window['go']['main']['App']['PinFlow'](arg1);
}

export function RemoveAllowBlockRule(arg1) {
  return window['go']['main']['App']['RemoveAllowBlockRule'](arg1);
}

export function RemoveBreakpointRule(arg1) {
  return window['go']['main']['App']['RemoveBreakpointRule'](arg1);
}

export function RemoveMapLocalRule(arg1) {
  return window['go']['main']['App']['RemoveMapLocalRule'](arg1);
}

export function RemoveReverseProxyRule(arg1) {
  return window['go']['main']['App']['RemoveReverseProxyRule'](arg1);
}

export function RemoveScript(arg1) {
  return window['go']['main']['App']['RemoveScript'](arg1);
}

export function RemoveUpstreamProxy(arg1) {
  return window['go']['main']['App']['RemoveUpstreamProxy'](arg1);
}

export function ReplayFlow(arg1) {
  return window['go']['main']['App']['ReplayFlow'](arg1);
}

export function ResumeBreakpoint(arg1) {
  return window['go']['main']['App']['ResumeBreakpoint'](arg1);
}

export function SendCustomRequest(arg1) {
  return window['go']['main']['App']['SendCustomRequest'](arg1);
}

export function SetAllowBlockMode(arg1) {
  return window['go']['main']['App']['SetAllowBlockMode'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestUpstreamProxy(arg1) {
  return window['go']['main']['App']['TestUpstreamProxy'](arg1);
}

export function UpdateAllowBlockRule(arg1) {
  return window['go']['main']['App']['UpdateAllowBlockRule'](arg1);
}

export function UpdateMapLocalRule(arg1) {
  return window['go']['main']['App']['UpdateMapLocalRule'](arg1);
}

export function UpdateReverseProxyRule(arg1) {
  return window['go']['main']['App']['UpdateReverseProxyRule'](arg1);
}

export function UpdateScript(arg1) {
  return window['go']['main']['App']['UpdateScript'](arg1);
}

export function UpdateUpstreamProxy(arg1) {
  return window['go']['main']['App']['UpdateUpstreamProxy'](arg1);
}

export function ValidateScript(arg1) {
  return window['go']['main']['App']['ValidateScript'](arg1);
}
