// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {features} from '../models';
import {export} from '../models';
import {proxycore} from '../models';

export function AddAllowBlockRule(arg1:features.AllowBlockRule):Promise<void>;

export function AddBreakpointRule(arg1:features.BreakpointRule):Promise<void>;

export function AddMapLocalRule(arg1:features.MapLocalRule):Promise<void>;

export function AddReverseProxyRule(arg1:features.ReverseProxyRule):Promise<void>;

export function AddScript(arg1:features.Script):Promise<void>;

export function AddUpstreamProxy(arg1:features.UpstreamProxy):Promise<void>;

export function CancelBreakpoint(arg1:string):Promise<void>;

export function ClearFlows():Promise<void>;

export function DecryptRequestBody(arg1:Array<number>,arg2:Record<string, string>):Promise<Array<number>>;

export function DecryptResponseBody(arg1:Array<number>,arg2:Record<string, string>):Promise<Array<number>>;

export function ExportFlows(arg1:export.ExportOptions):Promise<export.ExportResult>;

export function ExportFlowsToHAR(arg1:string):Promise<void>;

export function GetActiveBreakpoints():Promise<Array<features.BreakpointSession>>;

export function GetAllScripts():Promise<Array<features.Script>>;

export function GetAllowBlockMode():Promise<string>;

export function GetAllowBlockRules():Promise<Array<features.AllowBlockRule>>;

export function GetBreakpointRules():Promise<Array<features.BreakpointRule>>;

export function GetCACertInstallInstructions():Promise<string>;

export function GetCACertPath():Promise<string>;

export function GetFlowByID(arg1:string):Promise<proxycore.Flow>;

export function GetFlows():Promise<Array<proxycore.Flow>>;

export function GetMapLocalRules():Promise<Array<features.MapLocalRule>>;

export function GetPinnedFlows():Promise<Array<proxycore.Flow>>;

export function GetProxyPort():Promise<number>;

export function GetReverseProxyRules():Promise<Array<features.ReverseProxyRule>>;

export function GetUpstreamProxies():Promise<Array<features.UpstreamProxy>>;

export function ImportHARToFlows(arg1:string):Promise<Array<proxycore.Flow>>;

export function IsCACertInstalled():Promise<boolean>;

export function IsProxyRunning():Promise<boolean>;

export function ModifyAndReplayFlow(arg1:string,arg2:Record<string, any>):Promise<features.ReplayResponse>;

export function PinFlow(arg1:string):Promise<void>;

export function RemoveAllowBlockRule(arg1:string):Promise<void>;

export function RemoveBreakpointRule(arg1:string):Promise<void>;

export function RemoveMapLocalRule(arg1:string):Promise<void>;

export function RemoveReverseProxyRule(arg1:string):Promise<void>;

export function RemoveScript(arg1:string):Promise<void>;

export function RemoveUpstreamProxy(arg1:string):Promise<void>;

export function ReplayFlow(arg1:string):Promise<features.ReplayResponse>;

export function ResumeBreakpoint(arg1:string):Promise<void>;

export function SendCustomRequest(arg1:features.ReplayRequest):Promise<features.ReplayResponse>;

export function SetAllowBlockMode(arg1:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TestUpstreamProxy(arg1:string):Promise<void>;

export function UpdateAllowBlockRule(arg1:features.AllowBlockRule):Promise<void>;

export function UpdateBreakpointRuleStatus(arg1:string,arg2:boolean):Promise<void>;

export function UpdateMapLocalRule(arg1:features.MapLocalRule):Promise<void>;

export function UpdateReverseProxyRule(arg1:features.ReverseProxyRule):Promise<void>;

export function UpdateScript(arg1:features.Script):Promise<void>;

export function UpdateScriptStatus(arg1:string,arg2:boolean):Promise<void>;

export function UpdateUpstreamProxy(arg1:features.UpstreamProxy):Promise<void>;

export function ValidateScript(arg1:string):Promise<void>;
